# Generated by Django 3.0.5 on 2020-07-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(max_length=64),
        ),
    ]
